### ISSUE TITLE
test maxwell_calibration

### ISSUE THREAD

**Issue by k-okada** [mikeferguson/maxwell#4]
@mikeferguson First of all, thanks for writing https://github.com/ros-perception/calibration package, and I'm trying to use this packages to other robots and start writing setup helper program at https://github.com/ros-perception/calibration/pull/31 .
However, I still not confident with my program seems not working well
- pose_guesses marker start from origin coordinates as shown in following image, is it correct? I suppose this should start from arm_chain (from base to gripper) + armchain_cb.
- did you checked monocam_pipeline?
- why you set `arm_chain_cb: [1, 0, 1, 1, 1, 1]` in free_cb_locations.yaml, not '[1,1,1,1,1,1]'
- Could you provide me  /tmp/maxwell_calibration/cal_measurements.bag data so that I can check behavior of maxwell_calibration.sh script by my self.

![screenshot_from_2014-09-21 23 48 51](https://cloud.githubusercontent.com/assets/493276/4348855/7cf8c0cc-419e-11e4-8b2f-21eeec00e206.png)

**Comment by mikeferguson** [comment]
@k-okada see inline comments below:

> pose_guesses marker start from origin coordinates as shown in following image, is it correct? I suppose this should start from arm_chain (from base to gripper) + armchain_cb.

All the checkerboard poses start at the origin. The first calibration step adjusts only the checkerboard->arm transform and the poses themselves. In EVERY calibration step, the poses of the checkerboards area always completely free to move in 6-DOF space.

We did try bootstrapping the poses based off a single sensor and and an estimate of the checkerboard -> arm transform, however this usually resulted in hitting a local minima and overly worse results.

> did you checked monocam_pipeline?

I'm not sure what you are asking here... but I think maybe the monocam_pipeline has changed and no longer works with my exact config -- I haven't run this maxwell_calibration package in probably about 2 years.

> why you set arm_chain_cb: [1, 0, 1, 1, 1, 1] in free_cb_locations.yaml, not '[1,1,1,1,1,1]'

The assumption here is that the gripper closes on the Y-axis, and so the Y coordinate of the checkerboard should always be 0. Maxwell has only a single sensor, and allowing Y to be a free param tended to shift the gripper frame off into space, which was totally wrong. Overall, this calibration system is pretty finicky.

> Could you provide me /tmp/maxwell_calibration/cal_measurements.bag data so that I can check behavior of maxwell_calibration.sh script by my self.

I have to look around and see if I still have any bag files, I'm not sure I do...

**Comment by k-okada** [comment]
Thanks for comments, I think I managed to creates setup tool, see https://github.com/start-jsk/rtmros_hironx/pull/251.
I'm afraid that you did not remember the code you wrote in two years ago, but It seems you have assumption that frame_id of bag file and sytem.yaml should be identical. Is it correct?  https://github.com/ros-perception/calibration/pull/33. I also think arm_chain and head_chain should not share same joint/link chain. So we have to set base_link to the root of each leaf (arm and head).
