### ISSUE TITLE
Revive calibration

### ISSUE THREAD

**Issue by mikeferguson** [mikeferguson/maxwell#7]
The calibration stuff is horribly out of date and never worked that well. I intend to update this to use my newer calibration stuff over the next couple of weeks.

**Comment by jon-weisz** [comment]
Hey Mike, did you kill off the robot_geometry stuff in your old SVN repo for a reason?
I was thinking of making a simple calibration tool using the robot point cloud that is similar.

**Comment by mikeferguson** [comment]
Which robot_geometry stuff?

**Comment by mikeferguson** [comment]
Oh, the really old maxwell calibration stuff. Yeah, that never got finished, and then I ended up using the pr2_calibration after I removed PR2 stuff from it (that was fall of 2011 at WG). I'm now planning to end up using a generic version of the ubr_calibration (the start of it is over here: https://github.com/mikeferguson/robot_calibration), but I haven't had a ton of time to work on it.

**Comment by jon-weisz** [comment]
http://vanadium-ros-pkg.googlecode.com/svn/graveyard/maxwell_calibration_old/src/robot_geometry.cpp

**Comment by jon-weisz** [comment]
Yeah, I don't think this should really be on you. Calibration is really hard for beginners, and really easy to get wrong. Seems like making this stack a first class member of ROS would be really nice. Maybe we should propose it as a future OSRF SoC project?

**Comment by jon-weisz** [comment]
I know ros-industrial has this stuff: https://github.com/ros-industrial/industrial_calibration/ but it isn't complete yet either.

**Comment by mikeferguson** [comment]
Calibration is definitely an area that needs help in ROS -- however, having now worked on several calibration systems, I think you'd be quite hard pressed to have something that works for all situations (pr2_calibration is quite different from ubr_calibration, as the sensors are different, industrial calibration really only calibrates the camera positions as the assumption is that the mechanical system needs no calibration). Even if you could build something for all situations, I think it is a much larger project than could really be accomplished in a SoC sprint.

robot_calibration is intended for hand-eye calibration, primarily targeting kinect-like sensors, and will be getting quite a bit of work shortly, it just slid backwards in our schedule. It will certainly be done by summer, including a decent amount of documentation.

**Comment by mikeferguson** [comment]
Not going to implement calibration for Maxwell, since the robot is pretty much EOL. For anyone stumbling on this, check out robot_calibration on either the Fetch or the UBR-1: https://github.com/mikeferguson/ubr_reloaded/tree/ros2/ubr1_calibration
